services:
  # ① GoのAPIサーバーコンテナ
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql_db
    volumes:
      - ./processed:/app/processed
      - ./imports:/app/imports

    env_file:
      - .env

  # ② MySQLのデータベースコンテナ
  mysql_db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: music_db
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
